import { Ministry, Leadership } from '../types';

export const CBA_MINISTRIES: Ministry[] = [
  {
    "id": "min_infantil",
    "churchId": "church_cba_maceio",
    "name": "Ministério Infantil (Acolher Kids)",
    "leaderName": "Marcela da Mota Lins Queiroga",
    "viceLeaderName": "Alexia Brandão Gozele",
    "meetingDay": "Domingo",
    "meetingTime": "09:00 e 18:30",
    "location": "Salas do Acolher Kids",
    "description": "Ensino bíblico, acolhimento e discipulado de bebês e crianças durante as celebrações.",
    "membersCount": 12,
    "members": [
      "Marcela da Mota Lins Queiroga",
      "Alexia Brandão Gozele",
      "Alycia Vital",
      "Elton Casado Fireman",
      "Gerlanne Costa Alves Silva",
      "Jaqueline Maria da Silva",
      "Maria Eduarda Cavalcante Suica Oliveira",
      "Maria Flor Brandão Gozele",
      "Marina Libardi",
      "Silma Marisa Gardino Da Silva",
      "Walkiria Costa Alves dos Santos",
      "Yasmin Lessa da Silva Farias"
    ],
    "volunteers": [
      "Alice Agra Vasconcelos",
      "Ingrid Oliveira",
      "Nicolas Calazans Fireman",
      "Elisa Hilário Fireman"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_louvor",
    "churchId": "church_cba_maceio",
    "name": "Ministério de Louvor & Adoração (Música)",
    "leaderName": "Sandro de Melo do Espírito Santo",
    "viceLeaderName": "Amaury Luiz Lessa Neto",
    "meetingDay": "Sábado",
    "meetingTime": "16:00",
    "location": "Templo Principal",
    "description": "Condução do louvor congregacional, adoração bíblica, ensaios instrumentais e vocais.",
    "membersCount": 10,
    "members": [
      "Sandro de Melo do Espírito Santo",
      "Amaury Luiz Lessa Neto",
      "Isis Alane Gomes Miranda",
      "Itamar Vidal Silva de Lima",
      "Jadson Coutinho de Lima Filho",
      "José Chicuta Silva Neto",
      "Juliana Sarmento Vilela",
      "Ricardo Antônio Genuino Barroso",
      "Thirza de Almeida Barreto Souza",
      "Victor Oliveira Protásio"
    ],
    "volunteers": [
      "Bruno Rafael Ferreira de Melo",
      "Lízia Barobsa Fireman",
      "Sando Márcio Cirino",
      "Waneska Martins P. Cunha (Coral)",
      "Wannessa Kelly Wanderley Martins Borba",
      "Dalton Derley Remígio Lucas",
      "Maria Luiza Barros"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_midia",
    "churchId": "church_cba_maceio",
    "name": "Mídia, Tecnologia & Transmissão (Comunicação)",
    "leaderName": "Ruhan Nicolas Montenegro Oliveira",
    "viceLeaderName": "Mylenna Maria Amancio Correia",
    "meetingDay": "Quarta e Domingo",
    "meetingTime": "18:00",
    "location": "Mesa de Som e Cabine de Transmissão",
    "description": "Gestão de som, projeção, transmissão ao vivo no YouTube/Instagram e redes sociais da CBA.",
    "membersCount": 12,
    "members": [
      "Ruhan Nicolas Montenegro Oliveira",
      "Mylenna Maria Amancio Correia",
      "Ana Carolina Tenorio de Andrade Barbosa",
      "Ana Ruth de A B Souza",
      "Fábio Henrique da Silva Brito",
      "Guilherme Pietro Costa Alves dos Santos",
      "Ivo Thalisson Santos de Oliveira",
      "Jonas Emanuel Bento Assis de Melo",
      "Julio Cesar Sarmento Vilela de Barros",
      "Maria Luiza Barros",
      "Victor Oliveira Protásio",
      "Vinicius de Souza Leão"
    ],
    "volunteers": [
      "Davi Lucas Schinke Cavalcante Balbino",
      "Karlos Henriques Gouveia Borba",
      "Priscila Ingrid da Silva Alves",
      "Lucas Henrique de Souza Luz"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_cantina",
    "churchId": "church_cba_maceio",
    "name": "Ministério da Cantina & Comunhão",
    "leaderName": "Albany Hilana Faustino do Espírito Santo",
    "viceLeaderName": "Ana Paula Amorim",
    "meetingDay": "Domingo",
    "meetingTime": "17:00",
    "location": "Espaço de Convivência e Cantina CBA",
    "description": "Serviço de cantina, acolhimento gastronômico e momentos de comunhão pós-cultos.",
    "membersCount": 13,
    "members": [
      "Albany Hilana Faustino do Espírito Santo",
      "Ana Paula Amorim",
      "Ana Maria dos Santos Silva",
      "Cristiane Cavalcante Balbino",
      "Isis Alane Gomes Miranda",
      "Josefa Ferreira da Silva Santos",
      "Josivaldo Bento de Assis",
      "Juliana Costa Pinheiro Lessa",
      "Leonice Barbosa de Alcantara",
      "Maria das Dores Cariri dos Santos Silva",
      "Maria Selma Bento",
      "Nayra Vicente S. da Silva",
      "Nilza Simony Coutinho de Lima"
    ],
    "volunteers": [
      "Maria Selma Bento (Eventos)",
      "Maria Luiza Tenório de Almeida (Eventos)"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_social",
    "churchId": "church_cba_maceio",
    "name": "Ação Social (Amor em Ação)",
    "leaderName": "Mônica Lúcia Ferreira Silva de Lima",
    "viceLeaderName": "Pedro Caetano Marinho Araújo",
    "meetingDay": "Sábado (quinzenal)",
    "meetingTime": "09:00",
    "location": "Comunidades atendidas e Templo CBA",
    "description": "Distribuição de cestas básicas, visitas comunitárias e apoio a famílias em vulnerabilidade.",
    "membersCount": 7,
    "members": [
      "Mônica Lúcia Ferreira Silva de Lima",
      "Pedro Caetano Marinho Araújo",
      "Alaíne Silva Pereira",
      "Gabriel Caetano Marinho Araújo",
      "Jose Carlos Gomes patriota Júnior",
      "Maria Luiza Barros",
      "Wyda Eduarda Rocha Barros"
    ],
    "volunteers": [
      "Ariane Montenegro Alves Borges",
      "Franklin da Cruz Borges Junior",
      "Ítala Bento Mesquita",
      "Kamilla Kelly da Silva Peixoto",
      "Laísa Pereira da Silva",
      "Maria José Remígio Buarque",
      "Nazaré de Fátima Costa Melo",
      "Bruna Rafaela P. Fernandes",
      "Jeane da Silva Soares Monte Freitas"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_familia",
    "churchId": "church_cba_maceio",
    "name": "Ministério de Casais, Família & EBD",
    "leaderName": "Alyeskey Almeida",
    "viceLeaderName": "Renata Cristina da Mota Lins Queiroga",
    "meetingDay": "Sexta-feira (mensal)",
    "meetingTime": "19:30",
    "location": "Templo CBA",
    "description": "Encontros de casais, fortalecimento dos lares, aconselhamento conjugal e Escola Bíblica.",
    "membersCount": 10,
    "members": [
      "Alyeskey Almeida",
      "Renata Cristina da Mota Lins Queiroga",
      "Cleber Castanha de Queiroga",
      "Ednice Caetano Marinho Araujo",
      "Elcio Marques de Almeida",
      "Everaldo José da Silva",
      "Gerlanne Costa Alves Silva",
      "Hellen Aparecida Bueno Lourenço Almeida",
      "Walkiria Costa Alves dos Santos",
      "Weslley de Omena Santa Cruz"
    ],
    "volunteers": [
      "Jackeline Cristiane da Silva",
      "Jordana Ranielle Alves Araújo de Oliveira",
      "Juliana Costa Pinheiro Lessa"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_recepcao",
    "churchId": "church_cba_maceio",
    "name": "Ministério de Recepção & Boas-Vindas",
    "leaderName": "Jenice Coelho Rodrigues Cariri",
    "viceLeaderName": "Sando Márcio Cirino",
    "meetingDay": "Domingo",
    "meetingTime": "18:00",
    "location": "Porta de Entrada e Átrio do Templo",
    "description": "Primeiro contato, acolhimento de visitantes, entrega de folhetos e boletins.",
    "membersCount": 5,
    "members": [
      "Jenice Coelho Rodrigues Cariri",
      "Sando Márcio Cirino",
      "Ana Ruth de A B Souza",
      "Leonice Barbosa de Alcantara",
      "Neivaldo Ramos Pontes"
    ],
    "volunteers": [
      "Edvania Ramos de Melo Bitencourt",
      "Erika G Campos",
      "Jaelson Amorim de Vasconcelos",
      "Marcela da Mota Lins Queiroga",
      "Paulo Cesar Machado da Silva",
      "Ricardo Costa Bitencourt",
      "Weslley de Omena Santa Cruz",
      "Thais de Lima Santos",
      "Rosa Maria Schinke Cavalcante"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_juventude",
    "churchId": "church_cba_maceio",
    "name": "Juventude & Adolescentes (Conectados CBA)",
    "leaderName": "Marcos Henrique Noé da Silva",
    "viceLeaderName": "Charles Andrei Balbino Alves da Silva",
    "meetingDay": "Sábado",
    "meetingTime": "19:30",
    "location": "Templo CBA",
    "description": "Cultos de jovens, evangelismo criativo, comunhão, discipulado de adolescentes e juniores.",
    "membersCount": 6,
    "members": [
      "Marcos Henrique Noé da Silva",
      "Charles Andrei Balbino Alves da Silva",
      "Cristiane Oliveira de Souza Remígio",
      "Dalton Derley Remígio Lucas",
      "Gabriel Caetano Marinho Araújo",
      "Mylenna Maria Amancio Correia"
    ],
    "volunteers": [
      "Arthur Freitas Libardi",
      "Rosa Maria Schinke Cavalcante"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_fiscal",
    "churchId": "church_cba_maceio",
    "name": "Conselho Fiscal & Gestão Financeira",
    "leaderName": "Manoel Romão Neto",
    "meetingDay": "Mensal",
    "meetingTime": "19:00",
    "location": "Secretaria / Gabinete",
    "description": "Auditoria de contas, conferência de livros caixas, relatórios fiscais e prestação de contas.",
    "membersCount": 1,
    "members": [
      "Manoel Romão Neto"
    ],
    "volunteers": [],
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "min_mulheres",
    "churchId": "church_cba_maceio",
    "name": "Ministério de Mulheres & Intercessão",
    "leaderName": "Érica Renata Vilela de Morais",
    "viceLeaderName": "Hellen Aparecida Bueno Lourenço Almeida",
    "meetingDay": "Quinta-feira",
    "meetingTime": "19:30",
    "location": "Templo CBA",
    "description": "Edificação espiritual de mulheres, chás de comunhão, oração contínua e intercessão.",
    "membersCount": 4,
    "members": [
      "Érica Renata Vilela de Morais",
      "Hellen Aparecida Bueno Lourenço Almeida",
      "Ednice Caetano Marinho Araujo",
      "Juliana Sarmento Vilela"
    ],
    "volunteers": [
      "Ana Paula Amorim",
      "Elisabete Afra da Silva",
      "Jaqueline Silva de Ataíde",
      "Maria de Fátima e Silva",
      "Maria Rosa Gomes da Silva",
      "Patrícia de Souza Menezes",
      "Vilma Maria de Araújo Oliveira",
      "Wyda Eduarda Rocha Barros"
    ],
    "createdAt": "2026-01-15T10:00:00.000Z"
  }
];

export const CBA_LEADERSHIP: Leadership[] = [
  {
    "id": "lead_pastor_saulo",
    "churchId": "church_cba_maceio",
    "name": "Pr. Saulo Cavalcanti Monteiro",
    "role": "Pastor Titular",
    "phone": "(82) 99786-1774",
    "whatsapp": "5582997861774",
    "email": "saulomonteiro@cbacolher.com.br",
    "ministry": "Pastoral Geral",
    "startDate": "2020-01-01",
    "observations": "Pastor Presidente da Comunidade Batista Acolher.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_pastor_tercio",
    "churchId": "church_cba_maceio",
    "name": "Tercio Ribeiro de Souza",
    "role": "Equipe Pastoral",
    "phone": "(82) 98225-9873",
    "whatsapp": "5582982259873",
    "ministry": "Pastoral & Gabinete",
    "startDate": "2022-01-01",
    "observations": "Ministério Pastoral e Aconselhamento.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_fiscal_manoel",
    "churchId": "church_cba_maceio",
    "name": "Manoel Romão Neto",
    "role": "Presidente do Conselho Fiscal",
    "phone": "(82) 99331-1301",
    "whatsapp": "5582993311301",
    "ministry": "Conselho Fiscal & Financeiro",
    "startDate": "2024-01-01",
    "observations": "Responsável pela auditoria fiscal e financeira da igreja.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_infantil_marcela",
    "churchId": "church_cba_maceio",
    "name": "Marcela da Mota Lins Queiroga",
    "role": "Líder Ministério Infantil",
    "phone": "(81) 99225-2278",
    "whatsapp": "5581992252278",
    "ministry": "Acolher Kids",
    "startDate": "2023-02-01",
    "observations": "Coordenação pedagógica e espiritual das crianças.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_infantil_alexia",
    "churchId": "church_cba_maceio",
    "name": "Alexia Brandão Gozele",
    "role": "Vice-Líder Ministério Infantil",
    "phone": "(82) 99660-3258",
    "whatsapp": "5582996603258",
    "ministry": "Acolher Kids",
    "startDate": "2023-02-01",
    "observations": "Apoio na coordenação do Ministério Infantil.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_louvor_sandro",
    "churchId": "church_cba_maceio",
    "name": "Sandro de Melo do Espírito Santo",
    "role": "Ministro de Louvor",
    "phone": "(82) 99600-4790",
    "whatsapp": "5582996004790",
    "ministry": "Louvor & Adoração",
    "startDate": "2021-06-01",
    "observations": "Direção musical e adoração congregacional.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_louvor_amaury",
    "churchId": "church_cba_maceio",
    "name": "Amaury Luiz Lessa Neto",
    "role": "Vice-Líder de Louvor",
    "phone": "(82) 99415-8003",
    "whatsapp": "5582994158003",
    "ministry": "Louvor & Adoração",
    "startDate": "2022-01-01",
    "observations": "Apoio musical e vocal.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_midia_ruhan",
    "churchId": "church_cba_maceio",
    "name": "Ruhan Nicolas Montenegro Oliveira",
    "role": "Coordenador de Mídia e Transmissão",
    "phone": "(82) 99686-3870",
    "whatsapp": "5582996863870",
    "ministry": "Mídia e Tecnologia",
    "startDate": "2023-01-01",
    "observations": "Transmissão ao vivo, áudio e projeção.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_midia_mylenna",
    "churchId": "church_cba_maceio",
    "name": "Mylenna Maria Amancio Correia",
    "role": "Vice-Coordenadora de Mídia & Juventude",
    "phone": "(82) 99690-8463",
    "whatsapp": "5582996908463",
    "ministry": "Mídia e Juventude",
    "startDate": "2023-01-01",
    "observations": "Redes sociais, fotografia e comunicação jovem.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_cantina_albany",
    "churchId": "church_cba_maceio",
    "name": "Albany Hilana Faustino do Espírito Santo",
    "role": "Coordenadora da Cantina",
    "phone": "(82) 99656-4926",
    "whatsapp": "5582996564926",
    "ministry": "Cantina & Comunhão",
    "startDate": "2022-03-01",
    "observations": "Gestão da cantina, escalas e acolhimento.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_cantina_anapaula",
    "churchId": "church_cba_maceio",
    "name": "Ana Paula Amorim",
    "role": "Vice-Coordenadora da Cantina",
    "phone": "(72) 98869-4261",
    "whatsapp": "5572988694261",
    "ministry": "Cantina & Comunhão",
    "startDate": "2022-03-01",
    "observations": "Escalas e apoio à equipe da cantina.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_social_monica",
    "churchId": "church_cba_maceio",
    "name": "Mônica Lúcia Ferreira Silva de Lima",
    "role": "Líder de Ação Social",
    "phone": "(82) 99158-4774",
    "whatsapp": "5582991584774",
    "ministry": "Ação Social",
    "startDate": "2021-08-01",
    "observations": "Coordenação de projetos de caridade e apoio a famílias.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_social_pedro",
    "churchId": "church_cba_maceio",
    "name": "Pedro Caetano Marinho Araújo",
    "role": "Vice-Líder de Ação Social",
    "phone": "(82) 99812-3898",
    "whatsapp": "5582998123898",
    "ministry": "Ação Social",
    "startDate": "2022-01-01",
    "observations": "Logística de arrecadações e entregas comunitárias.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_familia_alyeskey",
    "churchId": "church_cba_maceio",
    "name": "Alyeskey Almeida",
    "role": "Líder do Ministério de Famílias",
    "phone": "(82) 99973-7979",
    "whatsapp": "5582999737979",
    "ministry": "Família, Casais & Homens",
    "startDate": "2021-01-01",
    "observations": "Aconselhamento, fortalecimento de lares e encontros de casais.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_familia_renata",
    "churchId": "church_cba_maceio",
    "name": "Renata Cristina da Mota Lins Queiroga",
    "role": "Vice-Líder de Famílias & EBD",
    "phone": "(81) 98160-1177",
    "whatsapp": "5581981601177",
    "ministry": "Família, Casais & EBD",
    "startDate": "2021-01-01",
    "observations": "Planejamento pedagógico e discipulado familiar.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_recepcao_jenice",
    "churchId": "church_cba_maceio",
    "name": "Jenice Coelho Rodrigues Cariri",
    "role": "Líder de Recepção & Acolhimento",
    "phone": "(82) 99999-2693",
    "whatsapp": "5582999992693",
    "ministry": "Recepção",
    "startDate": "2022-05-01",
    "observations": "Coordenação da equipe de recepção e boas-vindas da igreja.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_jovens_marcos",
    "churchId": "church_cba_maceio",
    "name": "Marcos Henrique Noé da Silva",
    "role": "Líder de Juventude",
    "phone": "(82) 99190-4266",
    "whatsapp": "5582991904266",
    "ministry": "Juventude Conectados CBA",
    "startDate": "2023-01-01",
    "observations": "Coordenação dos jovens e eventos da juventude.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  },
  {
    "id": "lead_mulheres_erica",
    "churchId": "church_cba_maceio",
    "name": "Érica Renata Vilela de Morais",
    "role": "Líder do Ministério de Mulheres",
    "phone": "(27) 99722-6463",
    "whatsapp": "5527997226463",
    "ministry": "Mulheres & Intercessão",
    "startDate": "2022-09-01",
    "observations": "Encontros e orações para mulheres da congregação.",
    "createdAt": "2026-01-15T10:00:00.000Z"
  }
];
