import { Schedule, ChurchEvent } from '../types';

export const CBA_SCHEDULES: Schedule[] = [
  {
    id: 'sched_cba_dom_noite',
    churchId: 'church_cba_maceio',
    title: 'Celebração Dominical',
    dayOfWeek: 'Domingo',
    tag: 'sun',
    time: '18:30',
    location: 'Templo Principal (Av. Júlio Marques Luz, 1409)',
    responsible: 'Pr. Tércio Ribeiro',
    description: 'Culto congregacional de celebração da família, adoração com louvor congregacional e ministração da Palavra. "A chama que nos move é o amor! ❤️‍🔥"',
    recurrence: 'semanal',
    createdAt: '2026-01-15T18:30:00.000Z'
  },
  {
    id: 'sched_cba_terca_encontro',
    churchId: 'church_cba_maceio',
    title: 'Terça do Encontro',
    dayOfWeek: 'Terça-feira',
    tag: 'tue',
    time: '19:30',
    location: 'Templo Principal',
    responsible: 'Pr. Tércio Ribeiro & Equipe Pastoral',
    description: 'Encontro semanal de oração, estudo bíblico aprofundado, renovo espiritual e comunhão no meio de semana.',
    recurrence: 'semanal',
    createdAt: '2026-01-15T19:30:00.000Z'
  },
  {
    id: 'sched_cba_dom_ebd',
    churchId: 'church_cba_maceio',
    title: 'Escola Bíblica Discipular (EBD)',
    dayOfWeek: 'Domingo',
    tag: 'sun',
    time: '10:00',
    location: 'Templo e Salas Educacionais',
    responsible: 'Renata Cristina Queiroga & Equipe de Ensino',
    description: 'Estudos bíblicos temáticos por faixas etárias: crianças, adolescentes, jovens, casais e adultos.',
    recurrence: 'semanal',
    createdAt: '2026-01-15T10:00:00.000Z'
  },
  {
    id: 'sched_cba_acolher_kids',
    churchId: 'church_cba_maceio',
    title: 'Acolher Kids (Culto Infantil)',
    dayOfWeek: 'Domingo',
    tag: 'sun',
    time: '18:30',
    location: 'Espaço Infantil Acolher Kids',
    responsible: 'Marcela da Mota & Alexia Brandão',
    description: 'Culto temático dinâmico, histórias bíblicas e acolhimento dedicado para crianças durante o culto noturno.',
    recurrence: 'semanal',
    createdAt: '2026-01-15T18:30:00.000Z'
  },
  {
    id: 'sched_cba_conectados_jovens',
    churchId: 'church_cba_maceio',
    title: 'Culto da Juventude - Conectados CBA',
    dayOfWeek: 'Sábado',
    tag: 'sat',
    time: '19:30',
    location: 'Templo Principal',
    responsible: 'Marcos Henrique Noé & Mylenna Correia',
    description: 'Culto jovem com louvor contemporâneo, mensagem inspiradora, dinâmicas e forte comunhão.',
    recurrence: 'quinzenal',
    createdAt: '2026-01-15T19:30:00.000Z'
  },
  {
    id: 'sched_cba_conexoes_pg',
    churchId: 'church_cba_maceio',
    title: 'Encontro das Conexões (Pequenos Grupos)',
    dayOfWeek: 'Quinta-feira',
    tag: 'thu',
    time: '20:00',
    location: 'Residências dos Líderes nos Bairros (Jatiúca, Ponta Verde, Serraria)',
    responsible: 'Liderança de Conexões',
    description: 'Comunhão fraternal, oração mútua e compartilhamento da Palavra de Deus nos lares.',
    recurrence: 'semanal',
    createdAt: '2026-01-15T20:00:00.000Z'
  }
];

export const CBA_EVENTS: ChurchEvent[] = [
  {
    id: 'event_cba_mulheres_2026',
    churchId: 'church_cba_maceio',
    name: 'Congresso de Mulheres Acolher: Curadas para Curar',
    bannerUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=1200&auto=format&fit=crop&q=80',
    startDate: '2026-10-24',
    endDate: '2026-10-25',
    time: '19:00',
    location: 'Templo CBA - Av. Júlio Marques Luz, 1409, Jatiúca',
    description: 'Edição oficial do Congresso de Mulheres da CBAcolher com preletoras convidadas, ministrações sobre restauração emocional, propósito e identidade em Deus. "A chama que nos move é o amor!"',
    responsible: 'Érica Renata Vilela & Ministério de Mulheres',
    registrationOpen: true,
    maxSpots: 250,
    spotsTaken: 114,
    createdAt: '2026-01-20T10:00:00.000Z'
  },
  {
    id: 'event_cba_retiro_2026',
    churchId: 'church_cba_maceio',
    name: 'Retiro Espiritual Acolher: Enquanto é Dia',
    bannerUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    startDate: '2026-11-14',
    endDate: '2026-11-17',
    time: '08:00',
    location: 'Sítio das Palmeiras - Região Metropolitana de Maceió',
    description: 'Dias intensos na presença do Senhor com tempo de consagração, oficinas bíblicas, lazer familiar e renovo espiritual completo para a congregação.',
    responsible: 'Pr. Tércio Ribeiro & Conselho Pastoral',
    registrationOpen: true,
    maxSpots: 180,
    spotsTaken: 92,
    createdAt: '2026-01-20T10:00:00.000Z'
  },
  {
    id: 'event_cba_casais_2026',
    churchId: 'church_cba_maceio',
    name: 'Conferência da Família & Casais: Edificados no Amor',
    bannerUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&auto=format&fit=crop&q=80',
    startDate: '2026-09-26',
    endDate: '2026-09-27',
    time: '19:30',
    location: 'Templo Principal CBA - Maceió',
    description: 'Fim de semana especial dedicado ao fortalecimento dos casamentos, princípios bíblicos para finanças no lar, educação dos filhos e edificação familiar.',
    responsible: 'Alyeskey Almeida & Ministério de Famílias',
    registrationOpen: true,
    maxSpots: 200,
    spotsTaken: 145,
    createdAt: '2026-01-20T10:00:00.000Z'
  },
  {
    id: 'event_cba_conectados_2026',
    churchId: 'church_cba_maceio',
    name: 'Conferência Conectados 2026: A Chama Que Nos Move',
    bannerUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    startDate: '2026-12-05',
    endDate: '2026-12-06',
    time: '19:00',
    location: 'Templo CBA',
    description: 'A grande conferência de juventude da CBAcolher com bandas convidadas de adoração, mensagens de impacto e clamor por despertamento espiritual.',
    responsible: 'Marcos Henrique Noé & Mylenna Correia',
    registrationOpen: true,
    maxSpots: 300,
    spotsTaken: 180,
    createdAt: '2026-01-20T10:00:00.000Z'
  },
  {
    id: 'event_cba_acao_social_2026',
    churchId: 'church_cba_maceio',
    name: 'Ação Social CBA: Amor em Ação',
    bannerUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1200&auto=format&fit=crop&q=80',
    startDate: '2026-10-12',
    time: '09:00',
    location: 'Comunidade Adjacente - Jatiúca / Maceió',
    description: 'Mutirão comunitário do Dia das Crianças com doação de cestas básicas, brinquedoteca com o Acolher Kids, cortes de cabelo gratuitos e acolhimento com a Palavra de Deus.',
    responsible: 'Mônica Lúcia Ferreira & Pedro Caetano',
    registrationOpen: true,
    maxSpots: 80,
    spotsTaken: 45,
    createdAt: '2026-01-20T10:00:00.000Z'
  },
  {
    id: 'event_cba_vigilia_2026',
    churchId: 'church_cba_maceio',
    name: 'Vigília Congregacional: Chama Viva',
    bannerUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?w=1200&auto=format&fit=crop&q=80',
    startDate: '2026-10-31',
    time: '22:30',
    location: 'Templo Principal CBA',
    description: 'Vigília de clamor pela cidade de Maceió, pelas famílias da igreja, pelos enfermos e busca intensa pela manifestação do Espírito Santo.',
    responsible: 'Pr. Tércio Ribeiro & Pr. Saulo Monteiro',
    registrationOpen: true,
    maxSpots: 200,
    spotsTaken: 88,
    createdAt: '2026-01-20T10:00:00.000Z'
  }
];
